// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB7Yzc0sbdg-SDMobWWzVbkitf-MCuEzc',
    appId: '1:395796610967:web:17da31e5593087db2dced2',
    messagingSenderId: '395796610967',
    projectId: 'donateconnect-22fa4',
    authDomain: 'donateconnect-22fa4.firebaseapp.com',
    storageBucket: 'donateconnect-22fa4.firebasestorage.app',
    measurementId: 'G-SMLBXDH1LR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd9VCJIreUzZLSqElQgXEQZq6S0kPY0fw',
    appId: '1:395796610967:ios:a4f5b88ecc90df342dced2',
    messagingSenderId: '395796610967',
    projectId: 'donateconnect-22fa4',
    storageBucket: 'donateconnect-22fa4.firebasestorage.app',
    iosBundleId: 'com.example.donationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB7Yzc0sbdg-SDMobWWzVbkitf-MCuEzc',
    appId: '1:395796610967:web:8962fcdd48c7d9162dced2',
    messagingSenderId: '395796610967',
    projectId: 'donateconnect-22fa4',
    authDomain: 'donateconnect-22fa4.firebaseapp.com',
    storageBucket: 'donateconnect-22fa4.firebasestorage.app',
    measurementId: 'G-MRQ8KXDXHP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd9VCJIreUzZLSqElQgXEQZq6S0kPY0fw',
    appId: '1:395796610967:ios:a4f5b88ecc90df342dced2',
    messagingSenderId: '395796610967',
    projectId: 'donateconnect-22fa4',
    storageBucket: 'donateconnect-22fa4.firebasestorage.app',
    iosBundleId: 'com.example.donationApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSS4V1AhoLGFd46KT6jqj91fuQLTxtIkk',
    appId: '1:395796610967:android:8eacd2be64b6fd262dced2',
    messagingSenderId: '395796610967',
    projectId: 'donateconnect-22fa4',
    storageBucket: 'donateconnect-22fa4.firebasestorage.app',
  );

}